Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -7,15 +7,8 @@ branding:
 
 inputs:
   tag:
-    description: 'Specify the Android kernel version and tag to build for (e.g., android14-5.15-2024-05).'
-    default: 'android14-5.15-2024-05'
-    required: true
-  simple-tag:
-    description: 'Simple Android kernel version and tag to build for (e.g., android14-5.15).'
-    default: 'android14-5.15'
-    required: true
-  version:
-    description: 'Kernel version. (e.g., 163)'
+    description: 'Specify the Android kernel version and tag to build for (e.g., android13-5.15).'
+    default: 'android13-5.15'
     required: true
   arch:
     description: 'Specify the architecture to build for (e.g., aarch64 or x86_64).'
@@ -26,9 +19,6 @@ inputs:
     required: true
   module-name:
     description: 'Specify the name of the kernel module.'
-    required: true
-  fast_build:
-    description: 'Enable LTO build?'
     required: true
 
 runs:
@@ -44,8 +34,8 @@ runs:
       shell: bash
       run: |
         VALID_TAGS=("android12-5.10" "android13-5.10" "android13-5.15" "android14-5.15" "android14-6.1" "android15-6.6" "android16-6.12")
-        if [[ ! " ${VALID_TAGS[@]} " =~ " ${{ inputs.simple-tag }} " ]]; then
-          echo "Invalid tag specified: ${{ inputs.simple-tag }}. Must be one of: ${VALID_TAGS[@]}"
+        if [[ ! " ${VALID_TAGS[@]} " =~ " ${{ inputs.tag }} " ]]; then
+          echo "Invalid tag specified: ${{ inputs.tag }}. Must be one of: ${VALID_TAGS[@]}"
           exit 1
         fi
         if [ ! -d "${{ inputs.module-name }}" ]; then
@@ -58,7 +48,8 @@ runs:
           exit 3
         fi
         if [ ! -f "${{ inputs.module-name }}/${{ inputs.module-name }}.c" ]; then
-          echo "Warning: ${{inputs.module-name}}/${{inputs.module-name}}.c does not exist."
+          echo "Error: ${inputs.module-name}/${inputs.module-name}.c does not exist."
+          exit 4
         fi
 
     - name: Install Build Tools
@@ -71,15 +62,8 @@ runs:
       shell: bash
       run: |
         sudo apt-get install -y repo
-        mkdir android-kernel
-        df -h android-kernel
-        cd android-kernel
-        repo init --depth=1 --u https://android.googlesource.com/kernel/manifest -b common-${{ inputs.tag }} --repo-rev=v2.16
-        REMOTE_BRANCH=$(git ls-remote https://android.googlesource.com/kernel/common ${{ inputs.tag }})
-        if grep -q deprecated <<< $REMOTE_BRANCH; then
-          echo "Warning: Found deprecated branch: ${{ inputs.tag }}"
-        fi
-        repo --version
+        mkdir android-kernel && cd android-kernel
+        repo init -u https://android.googlesource.com/kernel/manifest -b common-${{ inputs.tag }} --repo-rev=v2.16
         repo sync -c -j$(nproc) --no-tags
         df -h
 
@@ -119,17 +103,8 @@ runs:
       run: |
         pip install ast-grep-cli
         sudo apt-get install llvm-15 -y
-        
         ast-grep -U -p '$$$ check_exports($$$) {$$$}' -r '' common/scripts/mod/modpost.c
         ast-grep -U -p 'check_exports($$$);' -r '' common/scripts/mod/modpost.c
-        
-        if [[ "${{ inputs.simple-tag }}" == "android14-5.15" ]]; then
-          if [ "${{ inputs.arch }}" = "aarch64" ]; then
-            ast-grep -U -p 'static bool module_imports_namespace($$$ARGS) { return $AAA; }' -r 'static __attribute__((unused)) bool module_imports_namespace($$$ARGS) { return $AAA; }' common/scripts/mod/modpost.c
-            ast-grep -U -p 'static void check_for_gpl_usage($$$ARGS) { switch($A) {$$$B} }' -r 'static __attribute__((unused)) void check_for_gpl_usage($$$ARGS) { switch($A) {$$$B} }' common/scripts/mod/modpost.c
-          fi
-        fi
-        
         if [ -f common/android/gki_aarch64_modules ]; then
           echo "drivers/${{ inputs.module-name }}/${{ inputs.module-name }}.ko" >> common/android/gki_aarch64_modules
         fi
@@ -162,13 +137,11 @@ runs:
         cd common/ && git add -A && git commit -a -m "Add Kernel Module"
         repo status
 
-    - name: LTO Build Kernel
-      if: inputs.fast_build == 'true'
+    - name: Build Kernel
       shell: bash
       working-directory: android-kernel
       run: |
-        
-        if [[ "${{ inputs.simple-tag }}" == "android16-6.12" ]]; then
+        if [[ "${{ inputs.tag }}" == "android16-6.12" ]]; then
           if [ "${{ inputs.arch }}" = "aarch64" ]; then
             tools/bazel run --disk_cache=/home/runner/.cache/bazel --config=fast --lto=thin //common:kernel_aarch64_dist
           elif [ "${{ inputs.arch }}" = "x86_64" ]; then
@@ -179,45 +152,13 @@ runs:
             if [ -e build/build.sh ]; then
               LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh CC="/usr/bin/ccache clang"
             else
-              tools/bazel run --disk_cache=/home/runner/.cache/bazel --config=fast --config=stamp --lto=thin //common:kernel_aarch64_dist -- --dist_dir=dist
+              tools/bazel run --disk_cache=/home/runner/.cache/bazel --config=fast --lto=thin //common:kernel_aarch64_dist -- --dist_dir=dist
             fi
           elif [ "${{ inputs.arch }}" = "x86_64" ]; then
             if [ -e build/build.sh ]; then
               LTO=thin BUILD_CONFIG=common/build.config.gki.x86_64 build/build.sh CC="/usr/bin/ccache clang"
             else
-              tools/bazel run --disk_cache=/home/runner/.cache/bazel --config=fast --config=stamp --lto=thin //common:kernel_x86_64_dist -- --dist_dir=dist
-            fi
-          fi
-        fi
-
-    - name: Dev Build Kernel
-      if: inputs.fast_build == 'false'
-      shell: bash
-      working-directory: android-kernel
-      run: |
-        if [[ "${{ inputs.simple-tag }}" == "android14-5.15" ]]; then
-          tools/bazel run //common:db845c_abi_update_symbol_list
-          tools/bazel run //common:kernel_aarch64_abi_update
-          tools/bazel run //common:kernel_aarch64_abi_update -- --commit
-        fi
-        if [[ "${{ inputs.simple-tag }}" == "android16-6.12" ]]; then
-          if [ "${{ inputs.arch }}" = "aarch64" ]; then
-            tools/bazel run --disk_cache=/home/runner/.cache/bazel --config=fast --config=stamp --lto=none //common:kernel_aarch64_dist
-          elif [ "${{ inputs.arch }}" = "x86_64" ]; then
-            tools/bazel run --disk_cache=/home/runner/.cache/bazel --config=fast --config=stamp --lto=none //common:kernel_x86_64_dist
-          fi
-        else
-          if [ "${{ inputs.arch }}" = "aarch64" ]; then
-            if [ -e build/build.sh ]; then
-              LTO=none BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh CC="/usr/bin/ccache clang"
-            else
-              tools/bazel run --disk_cache=/home/runner/.cache/bazel --config=fast --config=stamp --lto=none //common:kernel_aarch64_dist -- --dist_dir=dist
-            fi
-          elif [ "${{ inputs.arch }}" = "x86_64" ]; then
-            if [ -e build/build.sh ]; then
-              LTO=none BUILD_CONFIG=common/build.config.gki.x86_64 build/build.sh CC="/usr/bin/ccache clang"
-            else
-              tools/bazel run --disk_cache=/home/runner/.cache/bazel --config=fast --config=stamp --lto=none //common:kernel_x86_64_dist -- --dist_dir=dist
+              tools/bazel run --disk_cache=/home/runner/.cache/bazel --config=fast --lto=thin //common:kernel_x86_64_dist -- --dist_dir=dist
             fi
           fi
         fi
@@ -225,14 +166,14 @@ runs:
     - name: Prepare Artifacts
       shell: bash
       run: |
-        if [[ "${{ inputs.simple-tag }}" == "android16-6.12" ]]; then
+        if [[ "${{ inputs.tag }}" == "android16-6.12" ]]; then
           if [ "${{ inputs.arch }}" = "aarch64" ]; then
             OUTDIR=android-kernel/out/kernel_aarch64/dist
           elif [ "${{ inputs.arch }}" = "x86_64" ]; then
             OUTDIR=android-kernel/out/kernel_x86_64/dist
           fi
         else
-          OUTDIR=android-kernel/out/${{ inputs.simple-tag }}/dist
+          OUTDIR=android-kernel/out/${{ inputs.tag }}/dist
           if [ ! -e $OUTDIR ]; then
             OUTDIR=android-kernel/dist
           fi
@@ -240,10 +181,10 @@ runs:
         mkdir output
         ls -al $OUTDIR/
         cp $OUTDIR/*Image* ./output/
-        cp $OUTDIR/${{ inputs.module-name }}.ko ./output/${{ inputs.simple-tag }}_${{ inputs.module-name }}.ko
+        cp $OUTDIR/${{ inputs.module-name }}.ko ./output/${{ inputs.tag }}_${{ inputs.module-name }}.ko
 
     - name: Upload Kernel Artifacts
       uses: actions/upload-artifact@v4
       with:
-        name: Image-with-Modules-${{ inputs.version }}-${{ inputs.arch }}
+        name: Image-${{ inputs.tag }}-${{ inputs.arch }}
         path: ./output/*
